import type { GrahaConfig } from '@/types'

export const GRAHAS: GrahaConfig[] = [
  {
    id: 'surya',
    name: 'Surya',
    subtitle: 'Income & Earning Power',
    emotion: 'The engine that fuels the family\'s financial engine',
    icon: '☀',
    color: '#E89F3C',
    questions: [
      { id: 's1', type: 'yesno', text: 'More than one source of income?', options: ['Yes', 'No', "Don't Know"] },
      { id: 's2', type: 'yesno', text: 'Income increased consistently over last 3 years?', options: ['Yes', 'No', "Don't Know"] },
      { id: 's3', type: 'yesno', text: 'Plan exists if income stops suddenly?', options: ['Yes', 'No', "Don't Know"] },
      { id: 's4', type: 'yesno', text: 'Income dependent on a single source only?', options: ['Yes', 'No', "Don't Know"], reverseScore: true },
      { id: 's5', type: 'yesno', text: 'Invested in skill development recently?', options: ['Yes', 'No', "Don't Know"] },
    ],
  },
  {
    id: 'chandra',
    name: 'Chandra',
    subtitle: 'Emergency & Financial Peace',
    emotion: 'The calm reserve that protects the family in a crisis',
    icon: '☾',
    color: '#8AB4D6',
    questions: [
      { id: 'c1', type: 'yesno', text: 'Emergency fund in place?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'c2', type: 'yesno', text: 'Family can survive 6 months without income?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'c3', type: 'yesno', text: 'Family can survive 12 months without income?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'c4', type: 'yesno', text: 'Always maintain liquid savings?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'c5', type: 'yesno', text: 'Loans taken during past emergencies?', options: ['Yes', 'No', "Don't Know"], reverseScore: true },
    ],
  },
  {
    id: 'mangal',
    name: 'Mangal',
    subtitle: 'Protection & Insurance',
    emotion: 'The armour against life\'s uncertainties',
    icon: '♂',
    color: '#D45D5D',
    questions: [
      { id: 'm1', type: 'yesno', text: 'Adequate life insurance in force?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'm2', type: 'yesno', text: 'Adequate health insurance for the family?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'm3', type: 'yesno', text: 'Personal accident cover in place?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'm4', type: 'yesno', text: 'Critical illness protection?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'm5', type: 'yesno', text: 'Coverage reviewed annually?', options: ['Yes', 'No', "Don't Know"] },
    ],
  },
  {
    id: 'budh',
    name: 'Budh',
    subtitle: 'Financial Discipline',
    emotion: 'The intelligence that governs money habits',
    icon: '☿',
    color: '#4CAF7D',
    questions: [
      { id: 'b1', type: 'yesno', text: 'Maintain a monthly budget?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'b2', type: 'yesno', text: 'Track household expenses regularly?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'b3', type: 'yesno', text: 'Debt under control (less than 30% of income)?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'b4', type: 'yesno', text: 'Follow a save-first approach?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'b5', type: 'yesno', text: 'Review major financial decisions carefully?', options: ['Yes', 'No', "Don't Know"] },
    ],
  },
  {
    id: 'guru',
    name: 'Guru',
    subtitle: 'Wealth Creation',
    emotion: 'The wisdom that multiplies family prosperity',
    icon: '♃',
    color: '#7B61FF',
    questions: [
      { id: 'g1', type: 'yesno', text: 'Investments linked to specific goals?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'g2', type: 'yesno', text: 'Invest regularly (SIP / systematic plan)?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'g3', type: 'yesno', text: 'Portfolio adequately diversified?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'g4', type: 'yesno', text: 'Investments beating inflation consistently?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'g5', type: 'yesno', text: 'Long-term wealth strategy in place?', options: ['Yes', 'No', "Don't Know"] },
    ],
  },
  {
    id: 'shukra',
    name: 'Shukra',
    subtitle: 'Lifestyle & Happiness',
    emotion: 'The balance between living well and saving well',
    icon: '♀',
    color: '#E87A9A',
    questions: [
      { id: 'sk1', type: 'yesno', text: 'Enjoy life without constant financial stress?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'sk2', type: 'yesno', text: 'Vacations planned and budgeted for?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'sk3', type: 'yesno', text: 'Lifestyle expenses under control?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'sk4', type: 'yesno', text: 'Avoid status-driven or impulse spending?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'sk5', type: 'yesno', text: 'Family Happiness Fund exists?', options: ['Yes', 'No', "Don't Know"] },
    ],
  },
  {
    id: 'shani',
    name: 'Shani',
    subtitle: 'Retirement & Dignity',
    emotion: 'The discipline that ensures a dignified sunset',
    icon: '♄',
    color: '#4A5568',
    questions: [
      { id: 'sn1', type: 'yesno', text: 'Retirement corpus calculated?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'sn2', type: 'yesno', text: 'Investing regularly toward retirement?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'sn3', type: 'yesno', text: 'Retirement gap identified?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'sn4', type: 'yesno', text: 'Projected retirement income sufficient?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'sn5', type: 'yesno', text: 'Post-retirement healthcare costs planned?', options: ['Yes', 'No', "Don't Know"] },
    ],
  },
  {
    id: 'rahu',
    name: 'Rahu',
    subtitle: 'Financial Risk',
    emotion: 'The shadow planet of illusion and temptation',
    icon: '☊',
    color: '#8B5CF6',
    questions: [
      { id: 'r1', type: 'yesno', text: 'Avoid get-rich-quick schemes?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'r2', type: 'yesno', text: 'Understand every investment made?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'r3', type: 'yesno', text: 'Avoid emotional financial decisions?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'r4', type: 'yesno', text: 'Seek professional guidance regularly?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'r5', type: 'yesno', text: 'Portfolio aligned to actual risk profile?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'r6', type: 'yesno', text: 'Do you know about inflation?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'r7', type: 'yesno', text: 'Do you know about market-risk?', options: ['Yes', 'No', "Don't Know"] },
    ],
  },
  {
    id: 'ketu',
    name: 'Ketu',
    subtitle: 'Legacy & Succession',
    emotion: 'The legacy that outlives the wealth creator',
    icon: '☋',
    color: '#D97706',
    questions: [
      { id: 'k1', type: 'yesno', text: 'Valid and updated Will in place?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'k2', type: 'yesno', text: 'Nominations updated across all assets?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'k3', type: 'yesno', text: 'Family aware of all asset details?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'k4', type: 'yesno', text: 'Clear succession plan exists?', options: ['Yes', 'No', "Don't Know"] },
      { id: 'k5', type: 'yesno', text: 'Legacy discussions held with family?', options: ['Yes', 'No', "Don't Know"] },
    ],
  },
]

export const GRAHA_COLORS: Record<string, string> = {
  surya: '#E89F3C',
  chandra: '#8AB4D6',
  mangal: '#D45D5D',
  budh: '#4CAF7D',
  guru: '#7B61FF',
  shukra: '#E87A9A',
  shani: '#4A5568',
  rahu: '#8B5CF6',
  ketu: '#D97706',
}

export const GRAHA_EMOJIS: Record<string, string> = {
  surya: '☀',
  chandra: '☾',
  mangal: '♂',
  budh: '☿',
  guru: '♃',
  shukra: '♀',
  shani: '♄',
  rahu: '☊',
  ketu: '☋',
}
