import type { GrahaConfig } from '@/types'

export const GRAHAS: GrahaConfig[] = [
  {
    id: 'surya',
    name: 'Surya',
    subtitle: 'Income & Earning Power',
    emotion: 'Your earning potential is the foundation of everything.',
    icon: '☀',
    color: '#E89F3C',
    questions: [
      { id: 's1', type: 'radio', text: 'How stable is your primary income source?', options: ['Very stable', 'Moderately stable', 'Somewhat variable', 'Highly variable', 'Unstable'] },
      { id: 's2', type: 'radio', text: 'How many income streams does your family have?', options: ['1', '2', '3', '4', '5+'] },
      { id: 's3', type: 'radio', text: 'What percentage of your income is passive?', options: ['0%', '1–10%', '11–25%', '26–50%', '50%+'] },
      { id: 's4', type: 'radio', text: 'How has your income trended over the last 3 years?', options: ['Steadily increasing', 'Stable with growth', 'Flat', 'Slightly declining', 'Declining'] },
      { id: 's5', type: 'radio', text: 'How confident are you about income stability in the next 5 years?', options: ['Very confident', 'Confident', 'Neutral', 'Concerned', 'Very concerned'] },
    ],
  },
  {
    id: 'chandra',
    name: 'Chandra',
    subtitle: 'Emergency Fund & Financial Peace',
    emotion: 'Peace of mind isn\'t a luxury. It\'s a necessity.',
    icon: '☾',
    color: '#8AB4D6',
    questions: [
      { id: 'c1', type: 'radio', text: 'How many months of expenses can you cover from savings?', options: ['None', '1–3 months', '3–6 months', '6–12 months', '12+ months'] },
      { id: 'c2', type: 'radio', text: 'Where is your emergency fund held?', options: ['Not created', 'Savings account', 'Fixed deposit', 'Liquid fund', 'Multiple instruments'] },
      { id: 'c3', type: 'radio', text: 'Have you faced an emergency expense in the last 2 years?', options: ['Yes, fully covered', 'Yes, partially covered', 'Yes, struggled', 'No emergencies', 'Prefer not to say'] },
      { id: 'c4', type: 'radio', text: 'How would you handle a sudden ₹5 lakh expense?', options: ['From savings', 'From investments', 'From credit card', 'From loan', 'Would struggle'] },
      { id: 'c5', type: 'radio', text: 'How often do you worry about unexpected expenses?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Constantly'] },
    ],
  },
  {
    id: 'mangal',
    name: 'Mangal',
    subtitle: 'Protection & Insurance',
    emotion: 'Protection isn\'t about fear. It\'s about responsibility.',
    icon: '♂',
    color: '#D45D5D',
    questions: [
      { id: 'm1', type: 'radio', text: 'Do you have a life insurance policy?', options: ['Yes, adequate cover', 'Yes, but inadequate', 'Yes, not sure', 'No, planning to', 'No'] },
      { id: 'm2', type: 'radio', text: 'Is your life insurance adequate for your family\'s needs?', options: ['Yes, fully', 'Mostly', 'Partially', 'Not sure', 'Not at all'] },
      { id: 'm3', type: 'radio', text: 'Do you have health insurance for the entire family?', options: ['Yes, comprehensive', 'Yes, basic', 'Only self', 'Only through employer', 'No'] },
      { id: 'm4', type: 'radio', text: 'Do you have critical illness or accident cover?', options: ['Both', 'Critical illness', 'Accident cover', 'Neither', 'Not sure'] },
      { id: 'm5', type: 'radio', text: 'When was the last time you reviewed your insurance?', options: ['Within 6 months', 'Within a year', '1–2 years ago', 'Over 2 years', 'Never'] },
    ],
  },
  {
    id: 'budh',
    name: 'Budh',
    subtitle: 'Financial Discipline',
    emotion: 'Small habits. Big results.',
    icon: '☿',
    color: '#4CAF7D',
    questions: [
      { id: 'b1', type: 'radio', text: 'Do you maintain a monthly budget?', options: ['Always', 'Most months', 'Sometimes', 'Rarely', 'Never'] },
      { id: 'b2', type: 'radio', text: 'What percentage of your income do you save monthly?', options: ['30%+', '20–30%', '10–20%', '0–10%', 'Nothing'] },
      { id: 'b3', type: 'radio', text: 'How do you track your expenses?', options: ['Detailed app tracking', 'Spreadsheet', 'Mental tracking', 'Bank statements', 'Don\'t track'] },
      { id: 'b4', type: 'radio', text: 'Do you pay credit card bills in full each month?', options: ['Always', 'Most months', 'Sometimes', 'Minimum payment', 'No credit card'] },
      { id: 'b5', type: 'radio', text: 'How would you describe your spending habits?', options: ['Very disciplined', 'Mostly disciplined', 'Splurge sometimes', 'Often impulsive', 'Very impulsive'] },
    ],
  },
  {
    id: 'guru',
    name: 'Guru',
    subtitle: 'Wealth Creation',
    emotion: 'Wealth isn\'t built in a day. It\'s built with intention.',
    icon: '♃',
    color: '#7B61FF',
    questions: [
      { id: 'g1', type: 'radio', text: 'What percentage of your income is invested?', options: ['30%+', '20–30%', '10–20%', '0–10%', 'Nothing'] },
      { id: 'g2', type: 'radio', text: 'What is your primary investment objective?', options: ['Wealth creation', 'Regular income', 'Capital preservation', 'Tax saving', 'Not sure'] },
      { id: 'g3', type: 'radio', text: 'How diversified is your investment portfolio?', options: ['Very diversified', 'Moderately', 'Slightly', 'Single asset', 'No investments'] },
      { id: 'g4', type: 'radio', text: 'Do you have exposure to equity markets?', options: ['Yes, significant', 'Yes, moderate', 'Yes, small', 'Through mutual funds', 'No'] },
      { id: 'g5', type: 'radio', text: 'What is your typical investment horizon?', options: ['10+ years', '5–10 years', '3–5 years', '1–3 years', 'Less than a year'] },
    ],
  },
  {
    id: 'shukra',
    name: 'Shukra',
    subtitle: 'Lifestyle & Happiness',
    emotion: 'Money is a tool. Happiness is the goal.',
    icon: '♀',
    color: '#E87A9A',
    questions: [
      { id: 'sk1', type: 'radio', text: 'What % of income goes to discretionary spending?', options: ['Under 10%', '10–20%', '20–30%', '30–50%', 'Over 50%'] },
      { id: 'sk2', type: 'radio', text: 'How satisfied are you with your current lifestyle?', options: ['Very satisfied', 'Satisfied', 'Neutral', 'Somewhat dissatisfied', 'Dissatisfied'] },
      { id: 'sk3', type: 'radio', text: 'Do you budget for experiences and travel?', options: ['Always', 'Often', 'Sometimes', 'Rarely', 'Never'] },
      { id: 'sk4', type: 'radio', text: 'How often do you feel financial stress?', options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Constantly'] },
      { id: 'sk5', type: 'radio', text: 'Are you comfortable with your current standard of living?', options: ['Very comfortable', 'Comfortable', 'Adequate', 'Struggling', 'Very difficult'] },
    ],
  },
  {
    id: 'shani',
    name: 'Shani',
    subtitle: 'Retirement & Dignity',
    emotion: 'Retirement isn\'t an age. It\'s a financial number.',
    icon: '♄',
    color: '#4A5568',
    questions: [
      { id: 'sn1', type: 'radio', text: 'At what age do you plan to retire?', options: ['Before 50', '50–55', '55–60', '60–65', 'Not sure'] },
      { id: 'sn2', type: 'radio', text: 'What % of current income will you need post-retirement?', options: ['Under 50%', '50–60%', '60–70%', '70–80%', 'Not calculated'] },
      { id: 'sn3', type: 'radio', text: 'Have you calculated your retirement corpus?', options: ['Yes, in detail', 'Yes, roughly', 'Started planning', 'No, but planning to', 'Never thought about it'] },
      { id: 'sn4', type: 'radio', text: 'Are you consistently investing for retirement?', options: ['Yes, tracking targets', 'Yes, but inconsistently', 'Started recently', 'Planning to start', 'No'] },
      { id: 'sn5', type: 'radio', text: 'Do you have pension or guaranteed post-retirement income?', options: ['Yes, adequate', 'Yes, partial', 'Through EPF/NPS only', 'Not sure', 'No'] },
    ],
  },
  {
    id: 'rahu',
    name: 'Rahu',
    subtitle: 'Financial Risk',
    emotion: 'Risk isn\'t about avoiding danger. It\'s about managing uncertainty.',
    icon: '☊',
    color: '#8B5CF6',
    questions: [
      { id: 'r1', type: 'radio', text: 'How much debt does your family have?', options: ['No debt', 'Less than 25% of assets', '25–50% of assets', '50–75% of assets', 'Over 75% of assets'] },
      { id: 'r2', type: 'radio', text: 'What is your debt-to-income ratio?', options: ['Under 10%', '10–20%', '20–30%', '30–40%', 'Over 40%'] },
      { id: 'r3', type: 'radio', text: 'How much of your net worth is in a single asset?', options: ['Under 20%', '20–40%', '40–60%', '60–80%', 'Over 80%'] },
      { id: 'r4', type: 'radio', text: 'Do you have a will or estate plan?', options: ['Yes, both', 'Yes, will only', 'Planning to create', 'No, but discussed', 'No'] },
      { id: 'r5', type: 'radio', text: 'How exposed are you to market volatility?', options: ['Very low', 'Low', 'Moderate', 'High', 'Very high'] },
    ],
  },
  {
    id: 'ketu',
    name: 'Ketu',
    subtitle: 'Legacy & Succession',
    emotion: 'The greatest wealth is what you leave behind.',
    icon: '☋',
    color: '#D97706',
    questions: [
      { id: 'k1', type: 'radio', text: 'Have you created a will?', options: ['Yes, registered', 'Yes, not registered', 'In process', 'Planning to', 'No'] },
      { id: 'k2', type: 'radio', text: 'Have you discussed inheritance with your family?', options: ['Yes, in detail', 'Yes, briefly', 'Planned discussion', 'Hesitant to discuss', 'No'] },
      { id: 'k3', type: 'radio', text: 'Do you have a succession plan for your assets?', options: ['Yes, documented', 'Yes, discussed', 'In planning', 'Considered', 'No'] },
      { id: 'k4', type: 'radio', text: 'Are your assets properly titled and nominated?', options: ['All of them', 'Most of them', 'Some of them', 'Not sure', 'No'] },
      { id: 'k5', type: 'radio', text: 'Have you considered setting up a trust?', options: ['Already have one', 'In process', 'Considering', 'Not sure', 'Never considered'] },
    ],
  },
]

export const GRAHA_COLORS: Record<string, string> = {
  surya: '#E89F3C',
  chandra: '#8AB4D6',
  mangal: '#D45D5D',
  budh: '#4CAF7D',
  guru: '#7B61FF',
  shukra: '#E87A9A',
  shani: '#4A5568',
  rahu: '#8B5CF6',
  ketu: '#D97706',
}

export const GRAHA_EMOJIS: Record<string, string> = {
  surya: '☀',
  chandra: '☾',
  mangal: '♂',
  budh: '☿',
  guru: '♃',
  shukra: '♀',
  shani: '♄',
  rahu: '☊',
  ketu: '☋',
}
